<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>Blt.MyWayNext.Importer</AssemblyTitle>
    <Product>Blt.MyWayNext.Importer</Product>
    <Copyright>Copyright ©  2024</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <PropertyGroup>
    <StartupObject />
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="backup.cs" />
    <Compile Remove="Blt.MywayNext.Importer.cs" />
    <Compile Remove="BusinessProxy.cs" />
    <Compile Remove="BusinessProxy2.0.cs" />
    <Compile Remove="BusinessProxy3.0.cs" />
    <Compile Remove="BusinessProxy4.0.cs" />
    <Compile Remove="BusinessProxy5.0.cs" />
    <Compile Remove="Program.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.8" />
  </ItemGroup>
</Project>